name: Style Check

on:
  pull_request:
    paths:
    - '.github/workflows/**'
    - 'src/**.cpp'
    - 'src/**.h'

jobs:
  stylecheck:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        run: echo "changed_files=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }}...HEAD | xargs)" >> $GITHUB_OUTPUT

      - name: Run style check
        id: style-check
        run: echo "reviews=$(python3 scripts/build/style.py ${{ steps.changed-files.outputs.changed_files }} | jq -s -c .)" >> $GITHUB_OUTPUT

      - name: Delete previous bot review comments
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const comments = await github.paginate(
              github.rest.pulls.listReviewComments,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                per_page: 100,
              }
            );
            for (const comment of comments) {
              // direct match to the GH Actions bot
              if (comment.user && comment.user.login === "github-actions[bot]") {
                  await github.rest.pulls.deleteReviewComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    comment_id: comment.id
                  });
              }
            }

      - name: Post review comments
        uses: actions/github-script@v8
        id: post-comments
        env:
          REVIEWS: ${{ steps.style-check.outputs.reviews }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const reviews = JSON.parse(process.env.REVIEWS || "[]");
            const pr = context.payload.pull_request;
            const commit_id = "${{ github.event.pull_request.head.sha }}";

            for (const review of reviews) {
                await github.rest.pulls.createReviewComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: pr.number,
                  body: review.body,
                  path: review.path,
                  line: review.line,
                  side: "RIGHT",
                  commit_id: commit_id
                });
            }
